/*
 jquery utils EZG v1.139
 accordion: based on jQuery Ui Accordion, cluetip: based on jQuery clueTip plugin  (http://www.opensource.org/licenses/mit-license.php)
 jQuery Nivo Slider v3.0.1, http://nivo.dev7studios.com, Copyright 2012, Dev7studios (http://www.opensource.org/licenses/mit-license.php)
 reflection.js v1.1 (c) 2006-2011 Christophe Beyls <http://www.digitalia.be> MIT-style license.
 easyAccordion 0.1 (c) 2010 Andrea Cima Serniotti (http://www.madeincima.eu) Dual licensed under the MIT (MIT-LICENSE.txt) and GPL (GPL-LICENSE.txt) licenses.
 parseQuery (c) 2008 Michael Manning (http://actingthemaggot.com) Dual licensed under the MIT (MIT-LICENSE.txt) and GPL (GPL-LICENSE.txt) licenses.
 FitVids 1.0.3  (c) 2013, Chris Coyier
 other scripts : http://www.ezgenerator.com  (c) 2015 Image-line
 */
var ua=window.navigator.userAgent.toLowerCase(),isAndroid=-1<ua.indexOf("android"),msie=ua.indexOf("msie "),msie11=ua.match(/trident.*rv\:11\./);(0<msie||msie11)&&$("html").addClass("ie");jQuery.fn.center=function(){this.css("top",Math.max(0,($(window).height()-$(this).outerHeight())/2)+"px");this.css("left",Math.max(0,($(window).width()-$(this).outerWidth())/2)+"px");return this};jQuery.fn.autoHeight=function(){this.css("height",$(window).height()+"px");return this};
jQuery.fn.getRandomArea=function(){var b=Math.floor(Math.random()*this.length);this.each(function(c,g){c!=b?$(g).empty():$(g).css({display:"block"})});return jQuery(this[b])};
jQuery.fn.updateMenu=function(b){url=(b?"":"../")+"documents/centraladmin.php";$.get(url,{process:"up"},function(b){-1!=b.indexOf("cookie_login--")&&1==b.split("cookie_login--")[1].split("--cookie_login")[0]&&($(".widget_remember_me").show(),$("#remember_me").show());if(!(-1<b.indexOf("<")&&-1==b.indexOf("categ--"))){var g=b.split("menue--")[1].split("--menue")[0];if(-1<b.indexOf("categ--")){var k=b.split("categ--")[1].split("--categ")[0],e=b.split("ssmenu--")[1].split("--ssmenu")[0];b=b.split("ttype--")[1].split("--ttype")[0];
include_categories_inmenu(k,e,b)}"none"!=g&&$(".login_form_logged").show().prev().hide();"all"==g?($("#mmenu .hidden, #smenu .hidden, .mmenu .hidden, .smenu .hidden").removeClass("hidden"),$(".hidden").parent(".smenu, #smenu, .mmenu, #mmenu")&&$(".hidden").removeClass("hidden")):$.each(g.split("|"),function(b,c){$("#"+c).removeClass("hidden")});isAndroid&&$(".mmenu").each(function(){$(this).next().is("ul")&&$(this).addClass("ar").click(function(b){var c=$(this).next("ul");c.hasClass("clicked")||(b.stopPropagation(),
b.preventDefault(),$(".clicked").removeClass("clicked").hide(),c.addClass("clicked").show())})})}});return!0};function setCookie(b,c,g,k){var e=new Date;e.setDate(e.getDate()+g);c=escape(c)+(null==g?"":"; expires="+e.toUTCString())+(null==k?"":"; path="+k);document.cookie=b+"="+c}function getCookie(b){var c,g,k,e=document.cookie.split(";");for(c=0;c<e.length;c++)if(g=e[c].substr(0,e[c].indexOf("=")),k=e[c].substr(e[c].indexOf("=")+1),g=g.replace(/^\s+|\s+$/g,""),g==b)return unescape(k)}
$.extend({getUrlVars:function(){var b=[],c;c=$(location).attr("href");for(var g=c.slice(c.indexOf("?")+1).split("&"),k=0;k<g.length;k++)c=g[k].split("="),b.push(c[0]),b[c[0]]=c[1];return b}});
function include_categories_inmenu(b,c,g){if($("#xm2").length){b=JSON.parse(b);$("html");var k=$("#xm2").attr("data-page"),e=0<$(".megamenu").length;$.each(b,function(b,m){var n="",u=0;if(k!=b)for(var A=0;A<Object.keys(m).length;A++){$v=m[A];var r="";if(r!=$v.id){var r=$v.id,r=-1==$v.pid,z=0;!0===0<$v.kids.length&&$.each($v.kids,function(b,c){z+=c.count});if((0<$v.count||0<z)&&r){var r=c.replace("%MenuItemUrl%",$v.permalink_cat).replace("%MenuItemText%",$v.name),B="";0<z&&$.each($v.kids,function(b,
f){if(0<f.count){for(var e=Object.keys(m).length-1;0<=e;e--)if(m[e].id==f.cid){var k=m[e];break}B+=c.replace("%MenuItemUrl%",k.permalink_cat).replace("%MenuItemText%",(4==g?"":"&rarr; ")+k.name)}});""!=B.trim()?(n=4==g?n+r.replace("</li>","<ul>"+B+"</ul></li>"):n+(r+B),u=1):n+=r}}}A=$("li#mi"+b);0<A.length?u?$(n).insertAfter(A):$(A).append("<ul>"+n+"</ul>"):e?$("<ul>"+n+"</ul>").appendTo($("#ci"+b+" .megamenu")):4==g&&($("#ci"+b).find("ul").length?$("<li>"+n+"</li>").prependTo($("#ci"+b).find("ul:first")):
$("#ci"+b).is("li")&&$("<ul>"+n+"</ul>").appendTo($("#ci"+b)))})}}function sortByProperty(b){return function(c,g){var k=0;c[b]<g[b]?k=-1:c[b]>g[b]&&(k=1);return k}}
jQuery.parseQuery=function(b,c){var g="string"===typeof b?b:window.location.search,k={f:function(b){return unescape(b).replace(/\+/g," ")}},k=jQuery.extend({},k,"object"===typeof b&&"undefined"===typeof c?b:c),e={};jQuery.each(g.match(/^\??(.*)$/)[1].split("&"),function(b,c){c=c.split("=");c[1]=k.f(c[1]);e[c[0]]=e[c[0]]?e[c[0]]instanceof Array?(e[c[0]].push(c[1]),e[c[0]]):[e[c[0]],c[1]]:c[1]});return e};
(function(b){b.fn.insertAtCaret=function(b){return this.each(function(g){if(document.selection)this.focus(),sel=document.selection.createRange(),sel.text=b,this.focus();else if(this.selectionStart||"0"==this.selectionStart){g=this.selectionStart;var k=this.selectionEnd,e=this.scrollTop;this.value=this.value.substring(0,g)+b+this.value.substring(k,this.value.length);this.focus();this.selectionStart=g+b.length;this.selectionEnd=g+b.length;this.scrollTop=e}else this.value+=b,this.focus()})}})(jQuery);
(function(b){b.fn.autogrow=function(c){this.filter("textarea").each(function(){var c=b(this),k=20<c.height()?c.height():20;c.css("lineHeight");var e=b("<div></div>").css({position:"absolute",top:-1E4,left:-1E4,width:b(this).width()-parseInt(c.css("paddingLeft"))-parseInt(c.css("paddingRight")),fontSize:c.css("fontSize"),fontFamily:c.css("fontFamily"),lineHeight:c.css("lineHeight"),resize:"none"}).appendTo(document.body),c=function(){var c=this.value.replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/&/g,
"&amp;").replace(/\n$/,"<br/>&nbsp;").replace(/\n/g,"<br/>").replace(/ {2,}/g,function(b){for(var c=0,e="";c<b.length-1;c++)e+="&nbsp;";return e+" "});e.html(c);b(this).css("height",Math.max(e.height()+1,k))};b(this).change(c).keyup(c).keydown(c);c.apply(this)});return this}})(jQuery);
(function(b){b.fn.pmeter=function(c){return this.each(function(){var c=b(this).attr("rel");"undefined"==c&&(c="");b(".out_pass_div"+c).css("width",b(this).width());b(this).keyup(function(){var k;k=b(this).val();k=null!==k.match(/^.{1,7}$/)?1:null!==k.match(/(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$/)?5:null!==k.match(/^.{12,}$/)?5:null!==k.match(/(?=^.{8,}$)(?=.*\d)(?![.\n])(?=.*[a-zA-Z]).*$/)?4:null!==k.match(/^[^0-9]{8,11}$/)?3:null!==k.match(/^[0-9]{8,}$/)?2:-1;var e="",
f="",m=30*k;switch(k){case 5:e="#00FF00";f="strong";break;case 4:e="#00FFFF";f="good";break;case 3:e="#F5AC00";f="average";break;case 2:e="#FF0000";f="weak";break;case 1:e="#C0C0C0";f="short";break;default:e=""}b(".inn_pass_div"+c).css("width",m).css("background-color",e);b(".pass_progress_text"+c).hide();""!=f&&b("#pwdptext_"+f+c).show();"short"!=f&&b("#selfreg_password").text("")})})}})(jQuery);
(function(b){b.fn.rtable=function(c){c=b.extend({min:0,max:200,acolor:"#555555",asize:25},c||{});return this.each(function(){var g=this,k="transparent transparent "+c.acolor,e=c.acolor+" transparent transparent",f="0 "+c.asize+"px "+c.asize+"px",m=c.asize+"px "+c.asize+"px 0";b(g).animate({height:c.min});var n=b('<div class="rtable_arrow" style="cursor:pointer;border-color:'+e+";border-style:solid;border-width:"+m+';height:0;width:0"></div>').click(function(){nh=b(g).hasClass("max");b(g).animate({height:nh?
c.min:c.max}).toggleClass("max");nh?b(n).css({"border-color":e,"border-width":m}):b(n).css({"border-color":k,"border-width":f});b(n).toggleClass("up")});0<b("."+this.className+"_footer").length?b("."+this.className+"_footer").after(n):b(g).after(n)})}})(jQuery);
(function(b){b.fn.poll=function(c){c=b.extend({id:"",root:!0},c||{});return this.each(function(){function g(c){b(c).find(".bar").hide().end().fadeIn("slow",function(){b(this).find(".bar").each(function(){var c=b(this).attr("rel");b(this).css("width","0").show().animate({width:c+"%"},1E3)})})}var k=this,e=b(k).find(".loader"),f=c.root?"":"../",m=b(k).find(".pc"),n="";e.fadeIn();b.get(f+"ezg_data/poll.php",{poll_id:c.id},function(c,A){-1<c.indexOf("include_once")?c="Upload to see poll working!":n=c.match("\x3c!--(.*)--\x3e")[1];
""!=n&&b(k).addClass(n);m.html(c);m.before(m.find(".poll_title"));g(m);m.find("#pollform").submit(function(){"undefined"!=typeof b(this).find("input[name=poll_answer]:checked").val()&&(e.fadeIn(),b.post(f+"ezg_data/poll.php",b(this).serialize(),function(c,f){m.find("#formcontainer").fadeOut(100,function(){b(this).html(c);g(this);e.fadeOut()})}));return!1});e.fadeOut()})})}})(jQuery);
(function(b){b.fn.ranking=function(c){c=b.extend({cnt:5,url:"",rsw:80,numbers:!1,vote:!1},c||{});return this.each(function(){function g(e,f){d=b(e).prevUntil(".ranking_result").addBack();f?d.addClass("ranking_star_active"):d.removeClass("ranking_star_active");c.numbers&&(f?d.css({opacity:.7}):d.css({opacity:1}))}function k(e,f,k){b(e).find(".ranking_progress").remove();pr=b('<span class="ranking_progress"'+(k?' onclick="$(this).remove()"':"")+"></span>");wi=f/c.cnt*c.rsw;c.numbers&&pr.css({opacity:.7});
pr.css({width:"0px"}).prependTo(e);pr.animate({width:wi+"px"})}if(b(this).hasClass("ready"))return!0;b(this).addClass("ready");var e=this,f=b(this).find(".ranking_result");val=b(f).text();id=b(f).attr("rel");dt=b(f).attr("data");voted="0"==dt;direct="2"==dt;rating=3==dt;voted||direct||f.empty().addClass("ranking_result_locked");if(c.vote)voted||(b(this).find(".ranking_result").append('<span class="ranking_vote"><i class="icon-thumbs-up"></i></span>'),b(this).find(".ranking_vote").click(function(){b.get(c.url,
{action:"ranking",entry_id:b(e).find(".ranking_result").attr("rel"),value:"1"},function(c){b(e).find(".ranking_result").empty().removeClass("ranking_result_locked").html("<span>"+c+"</span>")})}));else for(i=c.cnt;0<i;i--){f=b('<span class="ranking_star" rel="'+i+'">'+(c.numbers?"<span>"+i+"</span>":"")+"</span>");if(!voted||direct)f.mouseover(function(){g(this,!0)}).mouseout(function(){g(this,!1)}),f.click(function(){rating?(v=this.getAttribute("rel"),b(e).find(".rating_value").val(v),k(e,v,1)):
b.get(c.url,{action:"ranking",entry_id:b(e).find(".ranking_result").attr("rel"),value:this.getAttribute("rel")},function(c){b(e).find(".ranking_star").unbind("click");b(e).find(".ranking_result").empty().removeClass("ranking_result_locked").html("<span>"+c+"</span>");k(e,c,0)})});f.prependTo(e)}voted&&k(e,val,0);b(".ranking").css("visibility","visible")})}})(jQuery);
(function(b){b.fn.resizeImg=function(c){c=b.extend({max:0},c||{});return this.each(function(){var c=this,k=b(c).attr("rel").split(","),e=parseInt(k[0],10),f=parseInt(k[1],10),m=2<k.length,n="",u=b(c).width(),A=b(c).height(),r=b(c).outerWidth(!0),z=b(c).outerHeight(!0),B=b(c).css("float"),D=b(c).parent();3<k.length&&(n=k[3]);mar=D.hasClass("rvps1")?";margin:0 auto;":D.hasClass("rvps2")?";margin-left:auto;":"";b(c).css({"z-index":3,position:"absolute",left:0});b(c).wrap('<div style="position:relative;z-index:1;width:'+
r+"px;height:"+z+"px;float:"+B+mar+'" />');b(c).hover(function(){var k=-1<n.indexOf("l"),u=-1<n.indexOf("t");if(m&&""==n){var r=b(c).parents("td");null!=r&&(cx=b(r).parent().children(),col=cx.index(b(r)),rx=b(r).parent().parent().children(),row=rx.index(b(r).parent()),col==cx.length-1&&(k=1),row==rx.length-1&&(u=1))}zz={width:e+"px",height:f+"px"};k&&(zz.left="-"+(e/2+1)+"px");u&&(zz.top="-"+(f/2+1)+"px");b(this).parent().css({"z-index":2});b(this).stop().animate(zz,400)},function(){b(this).stop().animate({width:u+
"px",height:A+"px",left:"0px",top:"0px"},100,function(){b(this).parent().css("z-index",1)})})})}})(jQuery);
(function(b){b.fn.xzoom=function(c){c=b.extend({max:0,loupe:0,loupeSize:1.5},c||{});return this.each(function(){function g(){A=b(e).width();r=b(e).height();z=b(e).outerWidth(!0);B=b(e).outerHeight(!0);b(".zoomed_wrap",e).css({width:z,height:B});b(".mt").css({width:A,height:r})}function k(k){var g=new Image;g.src=b(k.currentTarget).prev().attr("src");m=g.width;f=m/A;u=Math.ceil(r/f);n=c.loupe?u+=50*c.loupeSize:Math.ceil(A/f);o=b(e).offset();oX=o.left;oY=o.top;x=k.pageX-oX;y=k.pageY-oY;c.loupe?(lx=
0>x?0:x>A?A-n:x-n/2,ly=0>y?0:y>r?r-u:y-u/2):(lx=x<n/2?0:x>A-n/2?A-n:x-n/2,ly=y<u/2?0:y>r-u/2?r-u:y-u/2);lx2=0>x?0:x>A?A-n:x;ly2=0>y?0:y>r?r-u:y}var e=this,f,m,n,u,A,r,z,B,D=b(e).css("float");p=b(e).parent();mar=p.hasClass("rvps1")?";margin:0 auto;":p.hasClass("rvps2")?";margin-left:auto;":"";b(e).wrap('<div class="zoomed_wrap" style="position:relative;cursor:move;z-index:1;float:'+D+mar+'" />');g();b("<img/>").attr("src",b(this).attr("src")).load(function(){mt=b('<div class="mt" style="position:absolute;top:0;left:0;z-index:100;background:url(.);width:'+
A+"px;height:"+r+'px" />').mouseenter(function(f){A==b(e).width()&&r==b(e).height()||g();bg="background:url("+b(e).attr("src")+");";c.loupe||(xz=b('<div class="zoomed" style="'+bg+"position:absolute;display:none;width:"+A+"px;height:"+r+"px;left:"+(A+5)+'px;top:0px;" />'),b(e).parent().append(xz),xz.fadeIn("fast"));k(f);b(e).parent().append('<div class="lens" style="'+(c.loupe?bg:"")+"position:absolute;top:"+ly+"px;left:"+lx+"px;width:"+(n-4)+"px;height:"+(u-4)+'px;" />')}).mousemove(function(g){k(g);
pX=lx*f;pY=ly*f;c.loupe?(pX=lx2*f-n/2,pY=ly2*f-u/2,b(e).parent().find(".lens").css({left:lx+"px",top:ly+"px","background-position":-pX+"px "+-pY+"px"})):(b(e).parent().find(".lens").css({left:lx+"px",top:ly+"px"}),b(e).parent().find(".zoomed").css({"background-position":-pX+"px "+-pY+"px"}))}).mouseleave(function(){b(e).parent().find(".zoomed,.lens").remove()});b(e).parent().append(mt)})})}})(jQuery);
(function(b){b.fn.x_accordion=function(c){c=b.extend({active:0,autoHeight:!0,updAct:"click",collapsible:!1,transDur:400,header:"",tab:""},c||{});return this.each(function(){function g(f){var k=b(u[e]),g=b(u[f]),m=g.css("overflow"),n=0,C={},E={},F;F=g[0].style.width;g.width(parseInt(g.parent().width(),10)-parseInt(g.css("paddingLeft"),10)-parseInt(g.css("paddingRight"),10)-(parseInt(g.css("borderLeftWidth"),10)||0)-(parseInt(g.css("borderRightWidth"),10)||0));b.each(["height","paddingTop","paddingBottom"],
function(c,e){E[e]="hide";var f=(""+b.css(g[0],e)).match(/^([\d+-.]+)(.*)$/);C[e]={value:f[1],unit:f[2]||"px"}});g.css({height:0,overflow:"hidden"}).show();k.animate(E,{step:function(b,c){"height"==c.prop&&(n=0===c.end-c.start?0:(c.now-c.start)/(c.end-c.start));g[0].style[c.prop]=n*C[c.prop].value+C[c.prop].unit},duration:c.transDur,complete:function(){g.css("height","");g.css({width:F,overflow:m})}})}function k(f){-1<e&&b(u[e]).stop(!0,!0);0>e?(b(u[f]).slideDown(c.transDur),e=f):f!=e?(b(n[e]).removeClass("active"),
g(f),e=f):(b(u[f]).slideToggle(c.transDur),e=b(n[f]).hasClass("active")?-1:f);b(n[f]).toggleClass("active")}var e=-1;if(null!=b(this)){var f=b(this).attr("id"),m=b.parseQuery();null!=m[f]&&(c.active=parseInt(m[f])-1);var n=b(c.header),u=b(c.tab).css({display:"none",zoom:"1"});n.each(function(f){b(n[f]).bind(c.updAct,function(b){k(f)})});-1<c.active&&k(c.active);this.slideTo=function(b){k(b)}}})}})(jQuery);
(function(b){b.fn.rssticker=function(c){c=b.extend({height:120,width:300,speed:1E3,autoplay:!0,delay:3E3,hor:!0,hidebtn:!0,count:1},c||{});return this.each(function(){function g(f,e){nh=0;e||(nh+=parseInt(b(z).find("li:last").attr("rel")));fi=f?b(z).children("li"):b(z).find("li:first").nextAll();b(fi).slice(0,e?c.count:c.count-1).each(function(){nh+=parseInt(b(this).attr("rel"))});return nh}function k(){clearTimeout(u);r&&(fi=b(z).find("li:first"),c.height=fi.height(),b(E).animate({height:g(0,1)},
c.speed));b(z).find("li:first").animate(c.hor?{marginLeft:"-"+c.width+"px"}:{marginTop:"-"+c.height+"px"},c.speed,function(){b(this).detach().appendTo(z).css(c.hor?{marginLeft:C}:{marginTop:D});!n&&c.autoplay&&e(0)})}function e(b){clearTimeout(A);A=setTimeout(k,0==b?c.delay:b)}function f(){n=0;c.hidebtn&&b(B).find(".ctrls").hide();e(0)}function m(){n=1;b(B).find(".ctrls").show();clearTimeout(A)}var n=0,u=0,A=0,r="auto"==c.height,z=this,B=b(this).parent();fi=b(z).find("li:first");fi_width=fi.width();
var D=b(fi).css("marginTop"),C=b(fi).css("marginLeft"),E=c.hor?B:z,F=b(z).find("li").length>c.count;r&&(b(z).find("li").each(function(){b(this).css("height",b(this).height())}),b(z).children("li").each(function(c){b(this).attr("rel",b(this).outerHeight(!0))}),b(E).css("height",g(1,1)));F&&(html='<div class="ctrls" style="'+(c.hidebtn?"display:none;":"")+'"><span class="ctrlup'+(c.hor?" hor":"")+'"></span><span class="ctrldo'+(c.hor?" hor":"")+'"></span></div>',b(html).appendTo(B),b(B).find(".ctrlup").click(function(){k()}),
b(B).find(".ctrldo").click(function(){clearTimeout(u);r&&(fi=b(z).find("li:last"),c.height=fi.height(),b(E).animate({height:g(1,0)},c.speed));b(z).find("li:last").detach().prependTo(z).css(c.hor?{marginLeft:"-"+c.width+"px"}:{marginTop:"-"+c.height+"px"}).animate(c.hor?{marginLeft:C}:{marginTop:D},c.speed)}));b(window).load(function(){function c(){fi.width()>f.width()||b("html").hasClass("resp")?(b(z).find("li.rs").width(f.width()),e=!0):e&&(b(z).find("li.rs").width(fi_width),e=!1)}var f=get_parent(z),
e=!1;c();b(window).resize(function(){c()})});c.autoplay&&F&&(navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/iPad/i)?b(z).bind("touchstart",function(){m()}).bind("touchend",function(){u=setTimeout(f,3E3)}):b(B).hover(function(){m()},function(){f()}),e(0))})}})(jQuery);
(function(b){b.fn.mmenu_animation=function(c){c=b.extend({animSpeed:500},c||{});return this.each(function(){var g="ontouchstart"in window,k=/iPad|iPod|iPhone/.test(navigator.platform)&&"matchMedia"in window;if(g&&!k){var e=b(".mmenu.level1");b(e).attr("rel","0").bind("touchstart",function(c){c="0"==b(this).attr("rel");b(e).attr("rel",0);b(this).attr("rel",c?"1":"0");this.focus()}).bind("click",function(c){"1"==b(this).attr("rel")&&c.preventDefault()})}b(this).children("li").each(function(){var f=
b(this),e=f.children(".megamenu");0<e.length?b(e).children("ul:first").css({visibility:"visible",display:"block"}):e=f.children("ul:first");e&&(e.css({display:"none"}),f.mouseover(function(b){e.hasClass("active")||e.addClass("active").stop(!0,!0).css({overflow:"hidden",height:"auto"}).animate({height:"show"},500,function(){e.css({overflow:"visible"})})}),f.mouseleave(function(b){e.stop(!0,!0).hide().removeClass("active")}),b(e).children("li").each(function(e,f){var k=b(f),g=k.children("ul:first");
g&&(g.css({display:"none"}),k.mouseover(function(b){g.hasClass("active")||g.addClass("active").animate({height:"show",width:"show"},c.animSpeed)}),k.mouseleave(function(b){g.stop(!0,!0).hide().removeClass("active")}))}))})})}})(jQuery);
(function(b){b.fn.float_login=function(c){c=b.extend({animSpeed:500,d:0,op:!1,pos:"top",cook:!1,path:"",pageid:0,lang:""},c||{});return this.each(function(){function g(){0<b(".logout_float").length&&b("#openLogin").hide()}function k(b){"left"==c.pos?b.animate({width:"show",marginLeft:"show",marginRight:"show",paddingLeft:"show",paddingRight:"show"},500):b.slideDown("slow")}function e(){b("#login_register,#forgot_pwd").click(function(c){c.preventDefault();b("#frm_login_error").empty();b.get(this.getAttribute("href"),
function(c){b("#register_form").hide().html(c).slideDown(500)})})}var f=this;b("#openLogin").click(function(){c.cook&&setCookie("fl_open","1","1000","/");k(b(f))});b("#closeLogin").click(function(){c.cook&&setCookie("fl_open","0","1000","/");var e=b(f);"left"==c.pos?e.animate({width:"hide",marginLeft:"hide",marginRight:"hide",paddingLeft:"hide",paddingRight:"hide"},500):e.slideUp("slow")});b("#toggle a").click(function(c){c.preventDefault();b("#toggle a").toggle()});fr_l=b("#frm_login");null!=fr_l&&
(fr_l.append('<input type="hidden" id="cc" name="cc" value="1"/>'),fr_l.submit(function(c){c.preventDefault();b(".frmhint").empty();b("#div_frm_login").addClass("ajl").css("opacity","0.2").delay(500);b.post(fr_l.attr("action"),fr_l.serialize(),function(c){b("#div_frm_login").removeClass("ajl").css("opacity","1");if("1"==c)cc=b(".frm_login #cc"),cc.val("0"),fr_l.unbind("submit"),fr_l.submit(),cc.val("1");else if("0"==c.charAt(0))for(errors=c.substring(1).split("|"),i=0;i<errors.length;i+=2)b("#frm_login_"+
errors[i]).append("<br />"+errors[i+1])})}));if(c.cook){var m=getCookie("fl_open");c.op=null==m||"1"==m}c.op&&(k(b(f)),b("#toggle a").toggle());c.d&&b(".logged_info").length?b.get(c.path+"documents/centraladmin.php",{process:"logged",lang:c.lang,root:""==c.path?1:0,vert:"left"==c.pos?1:0,pageid:c.pageid,nodw:1},function(c){data=b.parseJSON(c);b.each(data,function(c,f){0==c?b(".logged_info").replaceWith(f):b(".reg_links").prepend(f);e()});g()}):g()})}})(jQuery);
(function(b){b.fn.scrollbar=function(c){c=b.extend({slideInt:4E3,delay:4E3,navbar:!1,nb_numbers:!0,nb_hide:!1,rtl:!1,autoplay:!1,sc:!1,mw:1,tc:0,max:3,inf:0,scrollBymax:0,navw:80,cid:0,icont:"tc",iscroll:"t",cont:"g"},c||{});return this.each(function(){function g(e,f,k){var g=c.rtl,G=g?"right":"left",m={},u={},n={};m["margin-"+G]=g?f:-f;u["margin-"+G]=g?e:-e;f!=e&&C.css(m);C.animate(u,k?10:1E3);c.sc&&(p=100/(r.length-c.max),p*=c.cid,n[G]=p+"%",b(".ui-slider-handle").animate(n,1E3))}function k(e,f){el=
b('<div id="'+e+'"></div>');c.tc&&el.append(f);b(n).append(el);return el}function e(){m(u,0);G=setInterval(function(){m(u,0)},c.slideInt)}function f(e){c.inf||(ls=r.length-1,fr=100/ls,-1<e&&(c.cid=Math.floor(e/fr)),id=c.cid,0==id?b(S).hide():b(S).show(),id+c.max-1==ls?b(X).hide():b(X).show())}function m(e,k){c.navbar&&b(P[c.cid]).removeClass("active selected");k&&clearInterval(G);ls=r.length-1;inf=c.inf;id=c.cid;!inf&&(0==id&&0>e||0<e&&id+c.max>ls)?clearInterval(G):(F.stop(!0,!0),inf&&0>=id&&0>e?
(c.cid=ls+1+e,inx=c.cid+Q+u,sl=inx*z-I+M,ml=(inx+e)*z-I+M):inf&&id+e>ls&&0<e?(c.cid=0,inx=Q-u,sl=inx*z-I+M,ml=(inx+e)*z-I+M):(c.cid+=e,sl=ml=(c.cid+Q)*z-I+M),g(ml,sl,0));c.navbar&&b(P[c.cid]).addClass("active selected");f(-1)}var n=this,u=c.scrollBymax?c.max:1;if(null!=b("#"+c.cont+"_tc")){var A=b.parseQuery();null!=A[c.cont]&&(c.cid=parseInt(A[c.cont])-1);var r=b("#"+c.cont+"_tc .tb"),z=r.first().outerWidth(!1),B=r.first().width(),D=z-B,C=b("#"+c.cont+"_tc"),E=b(n).attr("id"),F=b("#"+c.cont+"_t"),
H=F.outerWidth(),G=0,Q=0,S="#"+c.cont+"_prev",X="#"+c.cont+"_next",I=c.rtl?C.width():0,M=c.rtl?z:0,A=r.length>c.max;if(c.sc){F.append('<div class="sc-bar-wrap"><div class="sc-bar"></div></div>');var T=b(".sc-bar").slider({slide:function(b,c){C.width()>F.width()?C.css("margin-left",Math.round(c.value/100*(F.width()-C.width()))+"px"):C.css("margin-left",0);f(c.value)}}),J=T.find(".ui-slider-handle").mousedown(function(){T.width(J.width())}).mouseup(function(){T.width("100%")}).wrap("<div class='ui-handle-helper-parent'></div>").parent();
F.css("overflow","hidden");setTimeout(function(){C.width();F.width();C.width();T.find(".ui-slider-handle").css({width:100,"margin-left":-50});J.width("").width(T.width()-100)},10)}A&&(k(E+"_next","&rsaquo;").bind("click",function(){m(u,1)}),k(E+"_prev","&lsaquo;").bind("click",function(){m(-u,1)}));if(c.navbar){el=b('<div class="'+c.cont+'_tc_navbar"></div>');r.each(function(e){a=b('<a class="'+c.cont+'_tc_navbar_item" style="outline:0" href="#">'+(c.nb_numbers?e+1:"&nbsp;")+"</a>").bind("click",
function(b){b.preventDefault();m(e-c.cid,1)}).bind("mouseenter",function(c){b(this).hasClass("selected")||b(this).addClass("active")}).bind("mouseleave",function(c){b(this).hasClass("selected")||b(this).removeClass("active")});b(el).append(a)});b(n).append(el);var P=b("."+c.cont+"_tc_navbar_item")}if(c.nb_hide){var V=b("."+c.cont+"_tc_navbar").hide();b("#"+c.cont).mouseenter(function(){b(V).animate({height:"show"},500)}).mouseleave(function(){b(V).animate({height:"hide"},500)})}-1==c.cid&&(c.cid=
Math.floor(Math.random()*(r.length-1-0+1)+0));c.inf&&A&&(C.append(r.slice(0,c.max).clone()),tl=r.length,C.prepend(r.slice(tl-c.max,tl).clone()),Q=c.max);E=(c.cid+Q)*z-I+M;A&&g(E,E,1);c.navbar&&b(P[c.cid]).addClass("active selected");f(-1);c.autoplay&&(G=setTimeout(e,c.delay),b(this).hover(function(){clearInterval(G)},function(){G=setTimeout(e,c.delay/2)}));b(window).load(function(){function e(b){th_w=1<u?G?b-D:B:b;z=th_w+D;C.attr("style","max-width: "+k.length*z+"px !important; width:"+k.length*z+
"px !important; margin-left:-"+(c.cid+(0<g?g:1))*z+"px");F.attr("style",G?"max-width: "+b+"px !important; width:"+b+"px !important":"");k.attr("style",G?"height: auto; overflow:auto; max-width: "+th_w+"px !important; width:"+th_w+"px !important;":"");I=c.rtl?C.width():0;M=c.rtl?z:0;k.find("div").css("max-width","100%")}function f(){H>m.width()||b("html").hasClass("resp")?(G=!0,e(m.width()>n?m.width()-n:m.width()-20)):G&&(G=!1,e(H))}var k=b("#"+c.cont+"_tc .tb"),g=parseInt((k.length-r.length)/2),G=
!1,m=get_parent(F),u=parseInt(H/z),n=b(S).width()+b(X).width();D=0<D?D:0;f();b(window).smartresize(function(){f()})});this.slideTo=function(b){m(b,1)}}})}})(jQuery);
(function(b){b.fn.x_tabs=function(c){c=b.extend({dir:"h",s:"#",slideInt:4E3,transDur:700,updAct:"click",anim:!0,autoplay:!0,stop:!0,id:0,ah:1,gmid:-1},c||{});return this.each(function(){function g(c){c=b(F[c]).find(".gmaps");c.length&&initialize(b(c).attr("id"))}function k(e){b(F[B]).stop(!0,!0);b(H[B]).removeClass("ct_act").addClass("ct");C&&b(E[B]).removeClass("ct_act").addClass("ct");c.anim?(du=c.transDur/2,b(F[B]).fadeOut(du,function(){b(this).hide();c.ah&&b(f).find(".di").css("height",b(F[e]).outerHeight());
b(F[e]).show();g(e);b(F[e]).hide();b(F[e]).fadeIn(du,function(){var c=b(F[e]);c.css("display","");b.support.opacity||c[0].style.removeAttribute("filter")})})):(b(F[B]).hide(),b(F[e]).show(),g(e));B=e;b(H[e]).removeClass("ct").addClass("ct_act");C&&b(E[e]).removeClass("ct").addClass("ct_act");ifr=b(F[e]).find(".ifr_ah");ifr.length&&(he=b(ifr).contents().height(),b(ifr).attr("height",he))}function e(){r=setInterval(function(){z=B;k(z+1>=F.length?0:z+1)},c.slideInt)}var f=this,m=b(f);if(null!=m){var n=
b(f).attr("id"),u="#"==c.s?"#"+n+"_":" .",A=b.parseQuery();null!=A[n]&&(c.id=parseInt(A[n])-1);var r=0,z=null,B=0;b(u+"di").show();var u="."+c.dir+"tab",A="."+c.dir+"div",D=c.dir+"_tabs_on",C=c.dir="h";if(!m.hasClass(D)){m.addClass(D);if(C)var E=b("#"+n).find(".litab");var F=b("#"+n).find(A).hide();0<c.id&&(B=0);var H=b("#"+n).find(u);k(c.id);c.autoplay&&e();H.each(function(e){b(H[e]).bind(c.updAct,function(b){B!=e&&(c.autoplay&&clearInterval(r),k(e));c.stop&&clearInterval(r)})});H.bind("mousedown",
function(){clearInterval(r)})}this.slideTo=function(b){c.autoplay&&clearInterval(r);k(b)}}})}})(jQuery);
(function(b){b.fn.cluetip=function(c,g){var k,e,f,m,n;"object"==typeof c&&(g=c,c=null);if("destroy"==c)return this.removeData("thisInfo").unbind(".cluetip");if(null!=b(this))return this.each(function(u){var A=this,r=b(this),z=b.extend({className:"default",width:0,height:"auto",dir:"auto",max:!1,tipDelay:0,offset:8,attribute:"rel",arrows:!0,sticky:!1,mouseOutClose:!1,clickThrough:!0,fixed:!1,truncate:0},g||{},b.metadata?r.metadata():b.meta?r.data():{});r.data("thisInfo",{title:A.title});b("#"+z.className).length||
(b(['<div id="'+z.className+'">','<div class="tip"><h3 class="tip-title"></h3><div class="tip-text"/><div class="cluetip-arrows"/></div></div>'].join("")).appendTo("body").hide(),k=b("#"+z.className).css({position:"absolute"}),f=b(".tip").css({position:"relative",zIndex:1003}),e=b(".tip-text"),m=b(".tip-title"),n=b(".cluetip-arrows"),z.sticky&&(b('<div id="cluetip-close" style="position:absolute;top:0;right:3px;font: bold 12px/12px Arial"><a href="#">x</a></div>').prependTo(f).bind("click.cluetip",
function(){Z();return!1}),z.mouseOutClose&&k.bind("mouseleave.cluetip",function(){Z()})));var B=r.attr(z.attribute),D=z.className,C=parseInt(z.offset,10),E="",F,H,G=isNaN(parseInt(z.height,10))?"auto":/\D/g.test(z.height)?z.height:z.height+"px",Q,S,X,I,M,T=parseInt(z.width,10),J=T+(parseInt(k.css("paddingLeft"),10)||0)+(parseInt(k.css("paddingRight"),10)||0),P,V,N,Y,O,K,L="title"!=z.attribute?r.attr("title"):"";void 0===L&&(L="");M=L.split("::");var L=M.shift(),W=function(f){k.removeClass();0<T&&
k.css({width:T});B==r.attr("href")&&r.css("cursor","help");th=r.children("a,img").length?r.children():r;V=b(th).outerHeight();P=b(th).outerWidth();S=X=b(th).offset().top;N=b(th).offset().left;O=f.pageX;Q=b(document).scrollTop();K=b(window).width();Y=P>N&&N>J&&0<J||N+P+J+C>K?N-J-C:P+N+C;if("area"===A.tagName.toLowerCase()||P+J>K)O+20+J>K?(k.addClass(D),Y=0<=O-J-C?O-J-C-parseInt(k.css("marginLeft"),10)+parseInt(e.css("marginRight"),10):O-J/2):Y=O+C;var g=0>Y?f.pageY+C:f.pageY;k.css({zIndex:1003});H=
b(window).height();c?("function"==typeof c&&(c=c.call(A)),e.html(c),0<z.tipDelay?setTimeout(function(){R(g)},z.tipDelay):R(g)):M&&(e.html(M.length?M[0]:""),0<z.tipDelay?setTimeout(function(){R(g)},z.tipDelay):R(g))},R=function(c){k.addClass(D);z.truncate&&(c=e.text().slice(0,z.truncate)+"...",e.html(c));b(".tip-text img").css("max-width",z.width-6);L?m.show().html(L):m.hide();e.css({overflow:"auto"==G?"visible":"auto"});z.max?e.css("max-height",G):e.css("height",G);F=k.outerHeight();J=k.outerWidth();
tipL=N+P/2-J/2;0>tipL&&(tipL=N);tipL>N&&P<J?tipL=N:tipL+J>K&&(tipL=K-J-5);I=S-F-C;E="top";if(I<Q||"bottom"===z.dir)I=S+V+C,E="bottom";"auto"===z.dir?(I+F-Q>H&&aa(),tipL+J>K-10&&U()):"right"===z.dir?aa():"left"===z.dir&&U();k.css({top:I,left:tipL}).removeClass().addClass(D+" tip_"+E);z.arrows&&n.show();k.fadeIn();b.fn.bgiframe&&k.bgiframe()},U=function(){I=S+V/2-F/2;tipL=N-J-5;E="left"},aa=function(){I=S+V/2-F/2;I<Q&&(I=Q+5);tipL=N+P+C;E="right"},Z=function(){f.parent().hide().removeClass();e.empty();
m.empty();r.removeClass("cluetip-clicked");L&&r.attr("title",L);r.css("cursor","");z.arrows&&n.css({top:""})};b(document).bind("hideCluetip",function(b){Z()});r[z.clickThrough?"unbind":"bind"]("click",function(){return!1});var ba=function(b){if(z.fixed){var c=Y-b.pageX,e=I?I-b.pageY:X-b.pageY;r.bind("mousemove.cluetip",function(b){k.css({left:b.pageX+c,top:b.pageY+e})})}};r.bind("mouseenter.cluetip",function(b){W(b);ba(b)}).bind("mouseleave.cluetip",function(b){z.sticky&&!/click|toggle/.test("hover")||
Z();r.unbind("mousemove.cluetip")});r.bind("mouseover.cluetip",function(b){r.attr("title","")}).bind("mouseleave.cluetip",function(b){r.attr("title",r.data("thisInfo").title)})})}})(jQuery);
(function(b){var c=function(c,k){var e=b.extend({},b.fn.nivoSlider.defaults,k),f={currentSlide:0,currentImage:"",totalSlides:0,running:!1,paused:!1,stop:!1,controlNavEl:!1,hideCap:!1},m=b(c);m.data("nivo:vars",f).addClass("nivoSlider");m.css("position","relative");b(".nivoSlider img").addClass("nivoI");b(".nivoI",m).css({position:"absolute",top:0,left:0});var n=m.children();n.each(function(){var c=b(this),e="";c.is("img")||(c.is("a")&&(c.addClass("nivo-imageLink"),e=c),c=c.find("img:first"));var k=
0===k?c.attr("width"):c.width(),g=0===g?c.attr("height"):c.height();""!==e&&e.hide();c.hide();f.totalSlides++});b(".nivo-imageLink",m).css({position:"absolute",top:0,left:0,width:"100%",height:"100%",display:"none","z-index":60,opacity:0,background:"#fff"});e.randomStart&&(e.startSlide=Math.floor(Math.random()*f.totalSlides));0<e.startSlide&&(e.startSlide>=f.totalSlides&&(e.startSlide=f.totalSlides-1),f.currentSlide=e.startSlide);b(n[f.currentSlide]).is("img")?f.currentImage=b(n[f.currentSlide]):
f.currentImage=b(n[f.currentSlide]).find("img:first");b(n[f.currentSlide]).is("a")&&b(n[f.currentSlide]).show();var u=b('<img class="nivo-main-image" src="#" />');u.attr("src",f.currentImage.attr("src")).show();m.append(u);b(window).resize(function(){e.scale&&m.children("img").width(m.width());u.attr("src",f.currentImage.attr("src"));u.stop().height("auto");b(".nivo-slice").remove();b(".nivo-box").remove()});m.append(b('<div class="nivo-caption"><div class="s_title"></div><div class="s_slogan"></div></div>').css({display:"none",
position:"absolute","z-index":"89"}));-1E4<e.t&&b(".nivo-caption",m).css({top:e.t,left:e.l});var A=function(c){var e=b(".nivo-caption",m);if(""!=f.currentImage.attr("title")&&void 0!=f.currentImage.attr("title")){var k="",g=f.currentImage.attr("title");"#"==g.substr(0,1)&&(g=b(g).html());p=g.indexOf("~");-1<p&&(k=g.substr(p+1),g=g.substr(0,p));"block"==e.css("display")?c.captionAni?b(".nivo-caption",m).fadeOut(c.animSpeed,function(){b(".nivo-caption .s_title",m).html(g);b(".nivo-caption .s_slogan",
m).html(k);b(this).fadeIn(c.animSpeed)}):setTimeout(function(){b(".nivo-caption .s_title",m).html(g);b(".nivo-caption .s_slogan",m).html(k)},c.animSpeed):(b(".nivo-caption .s_title",m).html(g),b(".nivo-caption .s_slogan",m).html(k),e.stop().fadeIn(c.animSpeed))}else e.stop().fadeOut(c.animSpeed)};-1E4<e.t&&b(".nivo-caption",m).css({top:e.t,left:e.l});e.hideCap||A(e);var r=0;!e.manualAdvance&&1<n.length&&(r=setInterval(function(){E(m,n,e,!1)},e.pauseTime));e.directionNav&&1<f.totalSlides&&(m.append('<div class="nivo-directionNav"><a class="nivo-prevNav">'+
e.prevText+'</a><a class="nivo-nextNav">'+e.nextText+"</a></div>"),e.directionNavHide&&(b(".nivo-directionNav",m).hide(),m.hover(function(){b(".nivo-directionNav",m).show()},function(){b(".nivo-directionNav",m).hide()})),b("a.nivo-prevNav",m).on("click",function(){if(f.running)return!1;clearInterval(r);r="";f.currentSlide-=2;E(m,n,e,"prev")}),b("a.nivo-nextNav",m).on("click",function(){if(f.running)return!1;clearInterval(r);r="";E(m,n,e,"next")}));if(e.controlNav){f.controlNavEl=b('<div class="nivo-controlNav"></div>');
m.after('<div class="clear"></div>');m.after(f.controlNavEl);for(var z=0;z<n.length;z++)if(e.controlNavThumbs){f.controlNavEl.addClass("nivo-thumbs-enabled");var B=n.eq(z);B.is("img")||(B=B.find("img:first"));B.attr("data-thumb")&&f.controlNavEl.append('<a class="nivo-control" rel="'+z+'"><img src="'+B.attr("data-thumb")+'" alt="" /></a>')}else f.controlNavEl.addClass("nivo-bullets"),f.controlNavEl.append('<a class="nivo-control" rel="'+z+'">'+(z+1)+"</a>");b("a:eq("+f.currentSlide+")",f.controlNavEl).addClass("active");
b("a",f.controlNavEl).bind("click",function(){if(f.running||b(this).hasClass("active"))return!1;clearInterval(r);r="";u.attr("src",f.currentImage.attr("src"));f.currentSlide=b(this).attr("rel")-1;E(m,n,e,"control")})}e.pauseOnHover&&m.hover(function(){f.paused=!0;clearInterval(r);r=""},function(){f.paused=!1;""!==r||e.manualAdvance||(r=setInterval(function(){E(m,n,e,!1)},e.pauseTime))});m.bind("nivo:animFinished",function(){u.attr("src",f.currentImage.attr("src"));f.running=!1;b(n).each(function(){b(this).is("a")&&
b(this).hide()});b(n[f.currentSlide]).is("a")&&b(n[f.currentSlide]).show();""!==r||f.paused||e.manualAdvance||(r=setInterval(function(){E(m,n,e,!1)},e.pauseTime));e.afterChange.call(this)});var D=function(c,e,f){b(f.currentImage).parent().is("a")&&b(f.currentImage).parent().show();b('img[src="'+f.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").width(e.scale?c.width():"").css("visibility","hidden").show();for(var k=b('img[src="'+f.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").parent().is("a")?
b('img[src="'+f.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").parent().height():b('img[src="'+f.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").height(),g=0;g<e.slices;g++){var m=Math.round(c.width()/e.slices);g===e.slices-1?c.append(b('<div class="nivo-slice" name="'+g+'"><img src="'+f.currentImage.attr("src")+'" style="position:absolute;'+(e.scale?"width:"+c.width()+"px;":"")+"height:auto; display:block !important; top:0; left:-"+(m+g*m-m)+
'px;" /></div>').css({left:m*g+"px",width:c.width()-m*g+"px",height:k+"px",opacity:"0",overflow:"hidden"})):c.append(b('<div class="nivo-slice" name="'+g+'"><img src="'+f.currentImage.attr("src")+'" style="position:absolute;'+(e.scale?" width:"+c.width()+"px;":"")+"height:auto; display:block !important; top:0; left:-"+(m+g*m-m)+'px;" /></div>').css({left:m*g+"px",width:m+"px",height:k+"px",opacity:"0",overflow:"hidden"}))}b(".nivo-slice",c).height(k);e.scale&&u.stop().animate({height:b(f.currentImage).height()},
e.animSpeed)},C=function(c,e,f){b(f.currentImage).parent().is("a")&&b(f.currentImage).parent().show();b('img[src="'+f.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").width(e.scale?c.width():"").css("visibility","hidden").show();for(var g=Math.round(c.width()/e.boxCols),k=Math.round(b('img[src="'+f.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").height()/e.boxRows),m=0;m<e.boxRows;m++)for(var n=0;n<e.boxCols;n++)n===e.boxCols-1?c.append(b('<div class="nivo-box" name="'+
n+'" rel="'+m+'"><img src="'+f.currentImage.attr("src")+'" style="position:absolute;'+(e.scale?"width:"+c.width()+"px;":"")+"height:auto; display:block; top:-"+k*m+"px; left:-"+g*n+'px;" /></div>').css({opacity:0,left:g*n+"px",top:k*m+"px",width:c.width()-g*n+"px"})):c.append(b('<div class="nivo-box" name="'+n+'" rel="'+m+'"><img src="'+f.currentImage.attr("src")+'" style="position:absolute;'+(e.scale?"width:"+c.width()+"px;":"")+"height:auto; display:block; top:-"+k*m+"px; left:-"+g*n+'px;" /></div>').css({opacity:0,
left:g*n+"px",top:k*m+"px",width:g+"px"})),b('.nivo-box[name="'+n+'"]',c).height(b('.nivo-box[name="'+n+'"] img',c).height()+"px");e.scale&&u.stop().animate({height:b(f.currentImage).height()},e.animSpeed)},E=function(c,e,f,g){var k=c.data("nivo:vars");k&&k.currentSlide===k.totalSlides-1&&f.lastSlide.call(this);if((!k||k.stop)&&!g)return!1;f.beforeChange.call(this);g?("prev"===g&&u.attr("src",k.currentImage.attr("src")),"next"===g&&u.attr("src",k.currentImage.attr("src"))):u.attr("src",k.currentImage.attr("src"));
k.currentSlide++;k.currentSlide===k.totalSlides&&(k.currentSlide=0,f.slideshowEnd.call(this));0>k.currentSlide&&(k.currentSlide=k.totalSlides-1);b(e[k.currentSlide]).is("img")?k.currentImage=b(e[k.currentSlide]):k.currentImage=b(e[k.currentSlide]).find("img:first");f.controlNav&&(b("a",k.controlNavEl).removeClass("active"),b("a:eq("+k.currentSlide+")",k.controlNavEl).addClass("active"));f.hideCap||A(f);b(".nivo-slice",c).remove();b(".nivo-box",c).remove();var m=f.effect;g="";"random"===f.effect&&
(g="sliceDownRight sliceDownLeft sliceUpRight sliceUpLeft sliceUpDown sliceUpDownLeft fold fade boxRandom boxRain boxRainReverse boxRainGrow boxRainGrowReverse slideInRight slideInLeft pushLeft".split(" "),m=g[Math.floor(Math.random()*(g.length+1))],void 0===m&&(m="fade"));-1!==f.effect.indexOf(",")&&(g=f.effect.split(","),m=g[Math.floor(Math.random()*g.length)],void 0===m&&(m="fade"));k.currentImage.attr("data-transition")&&(m=k.currentImage.attr("data-transition"));k.running=!0;var n=0,r=0,z=g=
"",E="";g="";if("sliceDown"===m||"sliceDownRight"===m||"sliceDownLeft"===m)D(c,f,k),r=n=0,g=b(".nivo-slice",c),"sliceDownLeft"===m&&(g=b(".nivo-slice",c)._reverse()),g.each(function(){var e=b(this);e.css({top:"0px"});r===f.slices-1?setTimeout(function(){e.animate({opacity:"1.0"},f.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+n):setTimeout(function(){e.animate({opacity:"1.0"},f.animSpeed)},100+n);n+=50;r++});else if("sliceUp"===m||"sliceUpRight"===m||"sliceUpLeft"===m)D(c,f,k),r=n=
0,g=b(".nivo-slice",c),"sliceUpLeft"===m&&(g=b(".nivo-slice",c)._reverse()),g.each(function(){var e=b(this);e.css({bottom:"0px"});r===f.slices-1?setTimeout(function(){e.animate({opacity:"1.0"},f.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+n):setTimeout(function(){e.animate({opacity:"1.0"},f.animSpeed)},100+n);n+=50;r++});else if("sliceUpDown"===m||"sliceUpDownRight"===m||"sliceUpDownLeft"===m){D(c,f,k);var B=r=n=0;g=b(".nivo-slice",c);"sliceUpDownLeft"===m&&(g=b(".nivo-slice",c)._reverse());
g.each(function(){var e=b(this);0===r?(e.css("top","0px"),r++):(e.css("bottom","0px"),r=0);B===f.slices-1?setTimeout(function(){e.animate({opacity:"1.0"},f.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+n):setTimeout(function(){e.animate({opacity:"1.0"},f.animSpeed)},100+n);n+=50;B++})}else if("fold"===m)D(c,f,k),r=n=0,b(".nivo-slice",c).each(function(){var e=b(this),k=e.width();e.css({top:"0px",width:"0px"});r===f.slices-1?setTimeout(function(){e.animate({width:k,opacity:"1.0"},f.animSpeed,
"",function(){c.trigger("nivo:animFinished")})},100+n):setTimeout(function(){e.animate({width:k,opacity:"1.0"},f.animSpeed)},100+n);n+=50;r++});else if("fade"===m)D(c,f,k),z=b(".nivo-slice:first",c),z.css({width:c.width()+"px"}),z.animate({opacity:"1.0"},2*f.animSpeed,"",function(){c.trigger("nivo:animFinished")});else if("slideInRight"===m)D(c,f,k),z=b(".nivo-slice:first",c),z.css({width:"0px",opacity:"1"}),z.animate({width:c.width()+"px"},2*f.animSpeed,"",function(){c.trigger("nivo:animFinished")});
else if("slideInLeft"===m)D(c,f,k),z=b(".nivo-slice:first",c),z.css({width:"0px",opacity:"1",left:"",right:"0px"}),z.animate({width:c.width()+"px"},2*f.animSpeed,"",function(){z.css({left:"0px",right:""});c.trigger("nivo:animFinished")});else if("pushLeft"==f.effect){b(".nivo-main-image",c).css("visibility","hidden");b(".nivo-imageLink",c).css({opacity:"1.0"});var n=r=0,H=c.width(),O,K,L;prev_slide=0==k.currentSlide?k.totalSlides-1:k.currentSlide-1;K=b(e[prev_slide]);O=K.is("img")?K:K.children();
L=b(e[k.currentSlide]);e=L.is("img")?L:L.children();null!=e&&e.css({display:"block"});L.css({left:H,display:"block"});K.css({left:0,display:"block"});null!=O&&O.css({display:"block"});K.animate({left:"-"+H},{step:function(b,c){"left"==c.prop&&(percentDone=0===c.end-c.start?0:(c.now-c.start)/(c.end-c.start));L.css({left:H-percentDone*H+"px"})},duration:2*f.animSpeed,complete:function(){null!=O&&O.css({display:"none"});K.css({display:"none",left:0});b(".nivo-slice",c).css({opacity:"1.0"});c.trigger("nivo:animFinished")}})}else if("boxRandom"===
m)C(c,f,k),E=f.boxCols*f.boxRows,n=r=0,g=F(b(".nivo-box",c)),g.each(function(){var e=b(this);r===E-1?setTimeout(function(){e.animate({opacity:"1"},f.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+n):setTimeout(function(){e.animate({opacity:"1"},f.animSpeed)},100+n);n+=20;r++});else if("boxRain"===m||"boxRainReverse"===m||"boxRainGrow"===m||"boxRainGrowReverse"===m){C(c,f,k);var E=f.boxCols*f.boxRows,W=n=r=0,R=0,U=[];U[W]=[];g=b(".nivo-box",c);if("boxRainReverse"===m||"boxRainGrowReverse"===
m)g=b(".nivo-box",c)._reverse();g.each(function(){U[W][R]=b(this);R++;R===f.boxCols&&(W++,R=0,U[W]=[])});for(e=0;e<2*f.boxCols;e++){k=e;for(g=0;g<f.boxRows;g++)0<=k&&k<f.boxCols&&(function(e,k,g,n,r){var u=b(U[e][k]),z=u.width(),E=u.height();"boxRainGrow"!==m&&"boxRainGrowReverse"!==m||u.width(0).height(0);n===r-1?setTimeout(function(){u.animate({opacity:"1",width:z,height:E},f.animSpeed/1.3,"",function(){c.trigger("nivo:animFinished")})},100+g):setTimeout(function(){u.animate({opacity:"1",width:z,
height:E},f.animSpeed/1.3)},100+g)}(g,k,n,r,E),r++),k--;n+=100}}},F=function(b){for(var c,e,f=b.length;f;c=parseInt(Math.random()*f,10),e=b[--f],b[f]=b[c],b[c]=e);return b},H=function(b){this.console&&"undefined"!==typeof console.log&&console.log(b)};this.stop=function(){b(c).data("nivo:vars").stop||(b(c).data("nivo:vars").stop=!0,H("Stop Slider"))};this.start=function(){b(c).data("nivo:vars").stop&&(b(c).data("nivo:vars").stop=!1,H("Start Slider"))};e.afterLoad.call(this);return this};b.fn.nivoSlider=
function(g){return this.each(function(k,e){var f=b(this);if(f.data("nivoslider"))return f.data("nivoslider");var m=new c(this,g);f.data("nivoslider",m)})};b.fn.nivoSlider.defaults={effect:"random",slices:15,boxCols:8,boxRows:4,t:-1E4,l:-1E4,animSpeed:1E3,pauseTime:3E3,startSlide:0,scale:!0,directionNav:!0,directionNavHide:!0,controlNav:!1,controlNavThumbs:!1,pauseOnHover:!0,manualAdvance:!1,prevText:"Prev",nextText:"Next",captionAni:!1,randomStart:!1,beforeChange:function(){},afterChange:function(){},
slideshowEnd:function(){},lastSlide:function(){},afterLoad:function(){}};b.fn._reverse=[].reverse})(jQuery);
jQuery.SmoothScroll=function(b){function c(b){return b.replace(/^\//,"").replace(/(index|default).[a-zA-Z]{3,4}$/,"").replace(/\/$/,"")}function g(c){c=$(c).offset().top;"undefined"!==typeof SmoothScrollOffset&&(c+=SmoothScrollOffset);$(e).animate({scrollTop:c},b,function(){})}var k=c(location.pathname),e=function(b){for(var c=0,e=arguments.length;c<e;c++){var k=arguments[c],g=$(k);if(0<g.scrollTop())return k;g.scrollTop(1);var r=0<g.scrollTop();g.scrollTop(0);if(r)return k}return[]}("html","body");
""!=location.hash&&(window.scrollTo(0,0),g(location.hash));$("a[href*=#]").each(function(){var b=c(this.pathname)||k;k!=b||location.hostname!=this.hostname&&this.hostname||!this.hash.replace(/#/,"")||this.hash&&$(this).click(function(b){b.preventDefault();g(this.hash)})})};
$.fn.extend({reflect:function(b){b=$.extend({height:.165,opacity:.5},b);return this.unreflect().each(function(){var c=this;if(/^img$/i.test(c.tagName)){var g=function(){var k=c.width,e=c.height,f,g,n,u;g=Math.floor(1<b.height?Math.min(e,b.height):e*b.height);f=$("<canvas />")[0];if(f.getContext){n=f.getContext("2d");try{$(f).attr({width:k,height:g}),n.save(),n.translate(0,e-1),n.scale(1,-1),n.drawImage(c,0,0,k,e),n.restore(),n.globalCompositeOperation="destination-out",u=n.createLinearGradient(0,
0,0,g),u.addColorStop(0,"rgba(255, 255, 255, "+(1-b.opacity)+")"),u.addColorStop(1,"rgba(255, 255, 255, 1.0)"),n.fillStyle=u,n.rect(0,0,k,g),n.fill()}catch(A){return}}$(f).css({display:"block",border:0});f=$(/^a$/i.test(c.parentNode.tagName)?"<span />":"<div />").insertAfter(c).append([c,f])[0];f.className=c.className;$.data(c,"reflected",f.style.cssText=c.style.cssText);$(f).css({width:k,height:e+g,overflow:"hidden"});c.style.cssText="display: block; border: 0px";c.className="reflected"};c.complete?
g():$(c).load(g)}})},unreflect:function(){return this.unbind("load").each(function(){var b=$.data(this,"reflected"),c;void 0!==b&&(c=this.parentNode,this.className=c.className,this.style.cssText=b,$.removeData(this,"reflected"),c.parentNode.replaceChild(this,c))})}});
(function(b){$.fn.livesearch=function(){function b(f){f="undefined"!==typeof f?f:"";q=g.val().trim();n=k.serialize();qR=n.replace(/\+/g,"");if(2>$.trim(q).length)$("#"+e).html("").hide();else if(qR!=u||""!=f)u=qR,$.ajax({url:k.attr("action")+"?"+n+"&action=search&x=1"+(""!=f?"&"+f+"=1":"")+"&livesearch_id="+e.replace("sid","")}).done(function(f){$("#"+e).html(f).show();$("#os_list").show();$("#livesearch_link"+e.replace("sid","")).on("click",function(){search_type_1=$(this).attr("data-stype").trim();
b("product_search"==search_type_1?search_type_1:"category_search")})})}var g=$(this),k=g.parents("form"),e="sid"+Math.floor(999999*Math.random());g.attr("autocomplete","off");0<$("#live_results").length?$("#live_results").append('<div id="'+e+'" class="pre-search-content" style="display: none;"></div>'):k.parent().append('<div id="'+e+'"  class="pre-search-content" style="width: '+k.width()+'px; background: white; display: none;"></div>');var f,m=!1,n="",u="";g.keyup(function(){clearTimeout(f);f=
setTimeout(b,300)});g.keydown(function(){clearTimeout(f)});g.blur(function(){m||$("#"+e).hide()});g.focus(function(){$("#"+e).show()});$("#"+e+",.filters_area").hover(function(){m=!0},function(){m=!1})}})(jQuery);
(function(b){b.fn.easyAccordion=function(c){var g={autoStart:!1,slideInterval:3E3,onHover:!1};this.each(function(){function k(){f.find("dt").each(function(){$(this).css({width:dtHeight,top:m,"margin-left":n})});f.find(".active").size()?f.find(".active").next("dd").addClass("active"):f.find("dt:first").addClass("active").next("dd").addClass("active");f.find("dt:first").css({left:"0"}).next().css({left:dtWidth});f.find("dd").css({width:ddWidth,height:ddHeight})}var e=b.extend(g,c),f=$(this);f.find("dl").addClass("easy-accordion");
b.fn.setVariables=function(b){b="undefined"!==typeof b?b:0;0<b&&$(this).width()>b?$(this).addClass("acc_respon"):$(this).hasClass("acc_respon")&&$(this).removeClass("acc_respon");dlWidth=$(this).width();dlHeight=$(this).height();dtWidth=$(this).find("dt").outerWidth(!1);dtHeight=$(this).find("dt").width();slideTotal=$(this).find("dt").size();ddWidth=dlWidth-dtWidth*slideTotal-($(this).find("dd").outerWidth(!0)-$(this).find("dd").width());ddHeight=dlHeight-($(this).find("dd").outerHeight(!0)-$(this).find("dd").height())};
$(window).load(function(){var b=get_parent(f);f.setVariables(b.width());k();f.calculateSlidePos(400);$(window).smartresize(function(){f.setVariables(b.width());k();f.calculateSlidePos(10)})});f.setVariables();k();var m=0,n=0,u,A;b.fn.findActiveSlide=function(){var b=1;this.find("dt").each(function(){$(this).hasClass("active")?u=b:$(this).hasClass("no-more-active")&&(A=b);b+=1})};b.fn.calculateSlidePos=function(c){var f=2;c="undefined"!==typeof c?c:400;$(this).find("dt").not(":first").each(function(){var b=
dtWidth*u;if(f<=u){var k=dtWidth*(f-1);1==e.onHover?$(this).stop(!0,!1).delay(400).animate({left:k},c):$(this).animate({left:k},c);f<u?$(this).next().css({left:k+dtWidth}):1==e.onHover?$(this).next().stop(!0,!1).delay(400).animate({left:b},c):$(this).next().animate({left:b},c)}else b=dlWidth-dtWidth*(slideTotal-f+1),1==e.onHover?$(this).stop(!0,!1).delay(400).animate({left:b},c):$(this).animate({left:b},c),b+=dtWidth,1==e.onHover?$(this).next().stop(!0,!1).delay(400).animate({left:b},c):$(this).next().animate({left:b},
c);f+=1});setTimeout(function(){b(".easy-accordion").find("dd").not(".active").each(function(){$(this).css({display:"none"})})},400)};b.fn.activateSlide=function(){this.parent("dl").setVariables();this.parent("dl").find("dd").css({display:"block"});this.parent("dl").find("dd.plus").removeClass("plus");this.parent("dl").find(".no-more-active").removeClass("no-more-active");this.parent("dl").find(".active").removeClass("active").addClass("no-more-active");this.addClass("active").next().addClass("active");
this.parent("dl").findActiveSlide();u<A&&this.parent("dl").find("dd.no-more-active").addClass("plus");this.parent("dl").calculateSlidePos()};b.fn.rotateSlides=function(b,c){var e=$(this);c.value=setTimeout(function(){e.rotateSlides(b,c)},b);$(this).findActiveSlide();var f=$(this).find("dt").size(),k=u+1;k>f&&(k=1);$(this).find("dt:eq("+(k-1)+")").activateSlide()};var r=new function(){this.value=null};$(this).findActiveSlide();$(this).calculateSlidePos();if(1==e.autoStart){var z=$(this),B=parseInt(e.slideInterval);
r.value=setTimeout(function(){z.rotateSlides(B,r)},B)}if(1==e.onHover){var D=new Date,C=D.getTime();$(this).find("dt").not("active").mouseover(function(){D=new Date;400<D.getTime()-C&&($(this).activateSlide(),clearTimeout(r.value),D=new Date,C=D.getTime())})}else $(this).find("dt").not("active").click(function(){$(this).activateSlide();clearTimeout(r.value)})})}})(jQuery);
(function(b){b.fn.utils_frmvalidate=function(b,g,k,e,f,m,n,u){return this.each(function(){var A=$(this),r=$(this).attr("id");m&&($(A).parent().after('<iframe name="dummy" style="display:none">'),$(A).attr("target","dummy"));A.prepend('<input type="hidden" class="cc" name="cc" value="1"/>');var z=""==document.referrer?window.location.href:document.referrer,B=$("#"+r+" :input[name=message]");B.length&&$("#"+r+" :input[name=message]").val(B.val().replace("%URL%",z));A.submit(function(m){A=$(this);r=
$(this).attr("id");m.preventDefault();n?($(".frmhint").remove(),$("#"+r+" .inputerror").removeClass("inputerror")):($(".frmhint").empty(),$("#"+r+" .input1").removeClass("inputerror"));k&&($("#div_"+r).css("opacity","0.6"),$(".loginDef_preloader").show());var z="";g&&$(":file").each(function(){z+="&up_"+$(this).attr("name")+"="+$(this).val()});$.post(A.attr("action"),A.serialize()+z,function(g){k&&($("#div_"+r).css("opacity","1"),$(".loginDef_preloader").hide());if("1"==g.charAt(0))g=$("#"+r+" .cc"),
g.val("0"),A.unbind("submit"),void 0!=u?u(A):A.submit(),g.val("1");else if("0"==g.charAt(0)){g=g.substring(1).split("|");for(i=0;i<g.length;i+=2)if(e){var m=$();f&&(m=$("#"+r+' *[name="'+g[i]+'"]').addClass("inputerror").parents("li:first"));m.length||(m=$("#"+r+" .ffooter"));$(m).append('<p class="rvts12 frmhint">'+g[i+1]+"</p>")}else $("#"+r+"_"+g[i]).append("<br />"+g[i+1]),$("#"+r+" input[name="+g[i]+"]").addClass("inputerror");b&&"function"==typeof reloadReCaptcha&&reloadReCaptcha()}else $("#div_"+
r).length?$("#div_"+r).html(g):$("#"+r+"_error").length&&$("#"+r+"_error").html(g)})})})}})(jQuery);function openhtml(b,c,g,k,e,f){f?ealert('<iframe width="'+g+'" height="'+k+'" src="'+c+'"></iframe>',"OK",k):ealert('<img style="max-width:100%;width:'+g+'px" src="'+c+'">',"OK",k);$(".emTitle").html(b);0!=e&&setTimeout("$('.emd').remove()",e)}var prev_color;function switch_cellcolor(b,c,g,k){prev_color=$(b.rows[c].cells[g]).css("background");$(b.rows[c].cells[g]).css("background",k)}
function rollover_on(b,c,g,k,e,f){el=$(b.target);if(!el.is("TABLE")&&(el.is("TD")||el.is("TH")||(el=$(el).parents("td,th")),$(el).length))if(ci=$(el)[0].cellIndex,ri=$(el)[0].parentNode.rowIndex,fr=""==k?0:1,fc=""==e?0:1,ri>=fr&&(f.ri=ri),ci>=fc&&(f.ci=ci),"TD"===g)ri>=fr&&ci>=fc&&switch_cellcolor(f,ri,ci,c);else{if("TR"!==g&&ci>=fc)for(x=fr;x<f.rows.length;x++)switch_cellcolor(f,x,ci,c);if("TC"!=g&&ri>=fr)for(x=fc;x<f.rows[ri].cells.length;x++)switch_cellcolor(f,ri,x,c)}}
function rollover_off(b,c,g,k,e,f){fr=""==k?0:1;fc=""==e?0:1;if("TD"===g&&f.rows[f.ri])$(f.rows[f.ri].cells[f.ci]).css("background",prev_color);else{if("TR"!==g)for(x=fr;x<f.rows.length;x++)$(f.rows[x].cells[f.ci]).css("background",prev_color);if("TC"!==g&&f.rows[f.ri])for(x=fc;x<f.rows[f.ri].cells.length;x++)$(f.rows[f.ri].cells[x]).css("background",prev_color)}}
function MultiSelector(b){this.list_target=b;this.id=0;this.addElement=function(b){if(null==b)return!1;"INPUT"==b.tagName&&"file"==b.type?(b.className=b.name="file_"+this.id++,b.multi_selector=this,b.onchange=function(){var b=document.createElement("input");b.type="file";this.parentNode.insertBefore(b,this);this.multi_selector.addElement(b);this.multi_selector.addListRow(this);$(this).css({position:"absolute",left:-1E3})},this.current_element=b):alert("Error")};this.addListRow=function(b){$(this.list_target).append('<input type="button" value=" '+
b.value+'  [x] " class="xbutton '+b.name+'" onclick="$(\'.'+b.name+"').remove();\">")}}var tog=1;function ToggleBody(b){b=$(b).parents(".block");tog&&($(b).removeClass("active"),$(".block.active").find(".blBody").slideUp(),$(".block.active").removeClass("active open"),$(b).addClass("active"));$(b).find(".blBody").slideToggle(function(){$(b).toggleClass("open")});return!1}var hda="",opa;
function initLogin(b,c){if(0==$("#"+b).length)return!1;$("#"+b).bind("mousedown",function(b){b.stopPropagation()});c&&$(document).bind("mousedown",function(b){""!=hda&&b.pageX<$(window).width()-15&&hide_Hdiv(hda)})}function responsive_hdiv(b,c,g,k,e){var f=$(window).width();$("#"+b).removeClass("resp_hdiv");$("#"+b).outerWidth()>f?($("#"+b).addClass("resp_hdiv"),0!=g&&$("#"+b).css({top:g})):(l=1==e?(f-c)/2:2==e||4==e?5:3==e||5==e?f-c-40:0,$("#"+b).css({left:l,top:k}))}
function show_Hdiv(b,c,g,k,e,f,m){if(0==$("#"+b).length)return!1;if(1==(null==m?0:m))if(ck=getCookie("hdiv"),null==ck&&(ck=""),-1==ck.indexOf("|"+b+"|"))setCookie("hdiv",ck+"|"+b+"|",c,"/");else{$("#"+b).remove();return}hda=b;h_dif=t=0;opa=null==k?1:k;pos=null==e?0:e;f=null==f?0:f;w=$(window).width();h=$(window).height();st=0==f?$(window).scrollTop():0;dw=$("#"+b).width();dh=$("#"+b).height();if(1==pos||4==pos||5==pos)h_dif=dh>h?10+st:0;else if(2==pos||3==pos)t=5+st;1==pos?(t=dh>h?h_dif:(h-dh)/2+
st,$("#"+b).css({left:(w-dw)/2,top:t})):2==pos?$("#"+b).css({left:5,top:t}):3==pos?$("#"+b).css({left:w-dw-40,top:t}):4==pos?(t=dh>h?h_dif:h-dh-45+st,$("#"+b).css({left:5,top:t})):5==pos&&(t=dh>h?h_dif:h-dh-45+st,$("#"+b).css({left:w-dw-40,top:t}));1==f&&$("#"+b).css({position:"fixed",overflow:"auto","max-height":"90%"});$("#"+b).fadeIn(c);0!=g&&(null!=g?$("#"+b).draggable({handle:"handle"}):$("#"+b).draggable());responsive_hdiv(b,dw,h_dif,t,pos);$(window).resize(function(){responsive_hdiv(b,dw,h_dif,
t,pos)})}function hide_Hdiv(b){$("#"+b).find(".yt").remove();hda="";$("#"+b).fadeOut(500)}function sClo(){$(".bkf_h").hide()}function sCls(){"undefined"!=typeof t&&clearTimeout(t)}function sTim(){t=setTimeout(sClo,1E3)}
function getImages(b,c){filter="img:not(.sb_img,.bullet,.cim,.bullet,.system_img)";obj=$(c).parents(".post_wrap").length?$(c).parents(".post_wrap").find(filter):$("#xm2 "+filter);obj.each(function(){60>$(this).width()||40>$(this).height()||(src=$(this)[0].src,url=b.replace("%MEDIA%",src),$(".sb_ul").append('<li><div class="img_block"><a href="'+url+'" target="_blank"><img class="sbp_img" src="'+src+'"/></a></div></li>'))})}
$(document).ready(function(){$(".bkc").hover(function(){bkf=$(this).children(".bkf");h=$(this).height();w=$(this).width();bw=$(bkf).width();winPos=$(window).scrollTop()+$(window).height();elPos=$(this).offset().top+h+$(bkf).height();$(bkf).css("top",winPos<elPos?"-"+$(bkf).height()+"px":h);winPos=$(window).scrollLeft()+$(window).width();elPos=$(this).offset().left+bw;$(bkf).css("left",winPos<elPos?"-"+(bw-w)+"px":0);$(bkf).show()},function(){sTim()});$(".bkf").hover(function(){sCls()},function(){sTim()});
$(".sb_pinterest").each(function(){$(this).click(function(b){$("body").append('<div class="sb_images"><img src="http://www.ezgenerator.com/social/pinterest.png"><a onclick="$(this).parent().remove();" class="close_btn"> X </a><ul class="sb_ul"></ul></div>');b.preventDefault();getImages($(this).attr("href"),this);$(".sb_images").css("top",($(window).height()-470)/2).show("fast")})})});
function loadCaptcha(b){var c=new Date;$("<img />").attr({src:b+"ezg_data/captcha.php?"+c.getTime(),"class":"system_img"}).load(function(){$("span.captcha").append($(this).clone(!0).unbind("load"));$(this).unbind("load");$("span.captcha img").click(function(c){$("span.captcha").empty();loadCaptcha(b)})})}
(function(b){b.fn.stickyC=function(c){function g(){b(window).scrollTop()>k?e.css({position:"fixed",top:"0px"}):e.css({position:"static",top:"auto"})}if(this.offset()){var k=this.offset().top;this.width();var e=this,f="undefined"==typeof c?b(this).closest("table,.div"):b(c),m=!1;f.css("position","relative");return f.height()<=e.position().top+e.height()+20?this:this.each(function(){b(window).scroll(function(){m||g();wh=f.height()+f.offset().top;sb=b(e).offset().top+e.height();wh-20<=sb?b(window).scrollTop()<
b(e).offset().top&&sb<wh?(m=!1,g()):(e.css({position:"absolute",top:f.height()-e.height()-20}),m=!0,f.height()<e.height()&&e.parent().css("height",e.height())):m=!1})})}}})(jQuery);
(function(b){b.fn.fitVids=function(c){var g={customSelector:null};if(!document.getElementById("fit-vids-style")){var k=document.createElement("div"),e=document.getElementsByTagName("base")[0]||document.getElementsByTagName("script")[0];k.className="fit-vids-style";k.id="fit-vids-style";k.style.display="none";k.innerHTML="&shy;<style>.fluid-width-video-wrapper{width:100%;position:relative;padding:0;}.fluid-width-video-wrapper iframe,.fluid-width-video-wrapper object,.fluid-width-video-wrapper embed {position:absolute;top:0;left:0;width:100%;height:100%;}</style>";
e.parentNode.insertBefore(k,e)}c&&b.extend(g,c);return this.each(function(){var c="iframe[src*='player.vimeo.com'] iframe[src*='youtube.com'] iframe[src*='youtube-nocookie.com'] iframe[src*='kickstarter.com'][src*='video.html'] object embed".split(" ");g.customSelector&&c.push(g.customSelector);c=b(this).find(c.join(",")).filter(".yt_auto");c=c.not("object object");c.each(function(){var c=b(this);if(!("embed"===this.tagName.toLowerCase()&&c.parent("object").length||c.parent(".fluid-width-video-wrapper").length)){var e=
0;isNaN(parseInt(c.attr("height"),10))||parseInt(c.attr("height"),10);isNaN(parseInt(c.attr("width"),10))||(e=parseInt(c.attr("width"),10));c.attr("id")||c.attr("id","fitvid"+Math.floor(999999*Math.random()));if(0==e||c.parent().parent().width()<e)c.removeAttr("height").removeAttr("width"),c.wrap('<div class="fluid-width-video-wrapper"></div>').parent(".fluid-width-video-wrapper").css("padding-top","56.25%")}})})}})(window.jQuery);
function arrowScrollTop(){xm1=$("#xm1,#i_content,body").first();$("body").append('<div id="scroll_arrow"><div class="arrow1"/><div class="arrow2"/></div>');$(window).scroll(function(){$(window).scrollTop()>xm1.position().top?$("#scroll_arrow").fadeIn("slow"):$("#scroll_arrow").fadeOut("fast")});$("#scroll_arrow").click(function(){$("html, body").animate({scrollTop:0},1E3);return!1})}
function detachMenu(){if($("nav").length){var b=$("nav").offset().top;1>b&&(b=1);$(window).scroll(function(){var c=$(window).scrollTop(),g=$("nav").offset().top;c>g?($("nav,#art-hmenu-bg").addClass("fix"),$("body").addClass("fixed_menu")):c<b&&($("nav,#art-hmenu-bg").removeClass("fix"),$("body").removeClass("fixed_menu"),$(window).trigger("resize"))})}}
function ealert(b,c,g){"undefined"===typeof c&&(c="OK");g="undefined"===typeof g?500:g+105;$("body").append('<div class="emd"><div class="emDlg" style="overflow-y: auto;overflow-x: hidden;bottom: 10px;max-height:600px; min-height:120px"><div class="emBody">'+b+'</div><div class="emFooter" ><span class="emTitle"></span><span class="emBtn">'+c+"</span></div></div></div>").addClass("ealert_body");setTimeout(function(){var b=$(".emBody").outerHeight()+$(".emFooter").outerHeight();$(".emDlg").height(g>
b&&0<b?b:g)},1);$(".emBtn").click(function(){$(".emd").remove();$("body").removeClass("ealert_body")})}function adminLink(b){$.ajax({type:"GET",url:b+"&adminlink=true",cache:!1,dataType:"html",success:function(c){-1!=c.indexOf('class="loginDef_preloader"')?($(".loginDef_overlay").remove(),$("body").append(c)):window.location.href=b}})}
$.fn.niceSelect=function(b){return this.each(function(){function c(b){return b.replace(b.substring(b.lastIndexOf("["),b.lastIndexOf("]")+1),"")}function g(b){u.obj_optn[b].isDisabled||(r.find(".selected_option").hide(),$.each(u.obj_optn,function(b,c){c.selected=!1}),u.obj_optn[b].selected=!0,u.obj_optn[b].el.find(".selected_option").show(),z.find(".firstValue_niceSelect").text(c(u.obj_optn[b].content)))}function k(b){if(!u.obj_optn[b].isDisabled){var e=u.obj_optn[b].el.find(".selected_option"),f=
!1;e.is(":visible")?(e.hide(),u.obj_optn[b].selected=!1,f=!0):(e.show(),u.obj_optn[b].selected=!0);var g="",k=!1;$.each(u.obj_optn,function(e,f){f.selected&&(k=!0,"all"==f.value&&"all"!=u.obj_optn[b].value||"all"==u.obj_optn[b].value&&"all"!=f.value?(f.selected=!1,f.el.find(".selected_option").hide()):g+=c(f.content)+" ")});D.empty().append(k||f?u.lang_l.confirm:u.lang_l.close);k||f?D.removeClass("submit_close"):D.addClass("submit_close");z.find(".firstValue_niceSelect").text(f&&!k?u.obj_optn[0].content:
g)}}function e(){var b=[],c=0;$.each(u.obj_optn,function(){this.selected&&(b[c++]=this.value)});G(!0);D.length&&D.hasClass("submit_close")||(0==b.length&&(b[0]=u.obj_optn[0].value),setTimeout(function(){f.val(b).change();"function"==eval("typeof "+u.onchange)&&eval(u.onchange+"("+JSON.stringify(u.obj_optn)+")")},400))}var f=$(this).css("display","none"),m=f.prop("multiple"),n=f.find("option"),u=$.extend({},{type:"color",onchange:"color_changed_niceSelect",obj_optn:[],old_sel:f,lang_l:{confirm:"confirm",
close:"close"}},b),A=$("<ul>"),r=$("<div>",{"class":"wrap_ul_niceSelect "+u.type}),z=$("<div>",{"class":"select_niceSelect"}),B=$("<div>",{"class":"wrap_niceSelect"}),D=m?$("<div>",{"class":"submit_niceSelect submit_close"}).append(u.lang_l.close).click(function(){e()}):"",C=function(){$(this).find(".arrow_1").addClass("hover_arrow")},E=function(){$(this).find(".arrow_1").removeClass("hover_arrow")},F=function(b){var c=$("<div>",{"class":"selected_option"});"color"==u.type&&c.append("&#10004;");u.obj_optn[b].selected&&
c.show();return c},H=function(b){var c=$("<span>");"all"==u.obj_optn[b].value&&"color"==u.type&&(u.obj_optn[b].data_style="background: linear-gradient(#1e5799 0%,#d628bc 12%,#fbff30 24%,#207cca 34%,#ff3033 45%,#58fc55 59%,#6d5014 72%,#2924bf 81%,#38931c 90%,#cc00c5 100%);");""!=u.obj_optn[b].data_style&&"undefined"!=u.obj_optn[b].data_style&&(u.obj_optn[b].data_style+=u.obj_optn[b].isDisabled?";opacity:0.4;":"",c.attr("style",u.obj_optn[b].data_style));return c},G=function(b){r.hasClass("openSelect")?
setTimeout(function(){r.slideUp("fast").removeClass("openSelect");z.removeClass("openSelect")},b?400:0):(r.slideDown("fast").addClass("openSelect"),z.addClass("openSelect"))};(function(){var b="";f.find("option:selected").each(function(){b+=$.trim(c($(this).text()))+" "});b=b.trim();n.each(function(f,n){u.obj_optn[f]={content:$.trim($(n).text()),value:$(n).val(),data_style:$(n).attr("data-style"),isDisabled:$(n).prop("disabled"),selected:$(n).is(":selected")?!0:!1,indx:f};is_color_value=!1;"color"==
u.type&&(void 0!=u.obj_optn[f].data_style?(arr_style=u.obj_optn[f].data_style.split(":"),"#;"!=arr_style[1]&&"#"!=arr_style[1]?is_color_value=!0:""==b&&(b=u.obj_optn[f].content)):is_color_value=!0);if(is_color_value){var r=$("<li>").append(H(f)).append(F(f)).click(function(){m?k(f):(g(f),e())}).hover(function(){u.obj_optn[f].isDisabled||$(this).addClass("hover_option")},function(){u.obj_optn[f].isDisabled||$(this).removeClass("hover_option")}).prop("title",m?c(u.obj_optn[f].content):u.obj_optn[f].content);
A.append(r);u.obj_optn[f].el=r}});z.click(function(){G(!1)}).append($("<div>",{"class":"firstValue_niceSelect"}).text(b)).append($("<div>",{"class":"arrow_niceSelect arrow_1"})).append($("<div>",{"class":"arrow_niceSelect arrow_2"})).hover(C,E);r.append(A).append(D);B.append(z).append(r).insertAfter(f)})()})};var m_loaded=0,m_visible=0,ios=navigator.userAgent.match(/(iPad|iPhone|iPod)/i),max_m,search_on=0,use_marquee=0;
function content_h(){max=$(window).height();mh=$("#ms_sitemap").height();$("#i_page_body").css("min-height",Math.max(mh,max))}function openmenu(b){$(b).parent().toggleClass("active");content_h()}function load_menu(b,c,g){$.get((c?"":"../")+"ezg_data/menu.php?id="+b+"&root="+c+"&lang="+g,function(c){$("#i_menu").html(c).hide();$(".id_"+b).addClass("active").parents("li:first").addClass("active");m_loaded=1;0<g&&($(".ms_lsitemap").not("#lang_"+g).hide().next().hide(),$(".level0").hide())})}
function toggle_menu(b){1==b?($("#i_menu").show(),content_h(),$("html, body").animate({scrollTop:0},"fast"),$("#i_page_body").animate({left:max_m},300,function(){m_visible=1;$("#i_topbar").css("position","absolute");ios&&$("#i_page_body").css("position","fixed")})):$("#i_page_body").animate({left:0},300,function(){m_visible=0;$("#i_topbar").css("position","fixed");$("#i_page_body").css("position","absolute");$("#i_menu").hide();$("#i_page_body").css("min-height",$(window).height())})}
function resize_search(){$("#i_search_box").css("width",$(window).width()-80)}function menu_pos(){sc_width=$(window).width();max_m=sc_width-60;265<max_m&&(max_m=265);1==search_on&&resize_search()}
function init_mobile(b,c,g,k){use_marquee=k;content_h();menu_pos();window.addEventListener("orientationchange",function(){menu_pos()},!1);load_menu(b,c,g);$("#i_button").click(function(){toggle_menu(0==m_visible);return!1});$("#i_search").click(function(){1==search_on?""==$("#i_search_box").val()?($("#i_search_container").hide(),search_on=!1):$("#i_searchform").submit():(resize_search(),$("#i_search_container").show(),search_on=1)});$("#i_content").on("touchend",function(b,c){1==m_visible&&(b.preventDefault(),
toggle_menu(0))});console.log($("#i_title").text().length);use_marquee&&25<$("#i_title").text().length&&titleMarquee()}function titleMarquee(){t=$("#i_title").text();$("#i_title").html('<marquee scrolldelay="85" scrollamount="6">'+t+"</marquee>")}function get_parent(b){var c=!1;$.each($(b).parents(),function(b,k){if(0<$(k).width())return c=$(k),!1});return c}
(function(b,c){var g=function(b,c,f){var g;return function(){var n=this,u=arguments;g?clearTimeout(g):f&&b.apply(n,u);g=setTimeout(function(){f||b.apply(n,u);g=null},c||50)}};jQuery.fn[c]=function(b){return b?this.bind("resize",g(b)):this.trigger(c)}})(jQuery,"smartresize");
$(document).ready(function(){if(1==$(".global_slideshow").length){var b=parseInt($("#xm2").attr("data-root"));$(".global_slideshow").each(function(){sid=parseInt($(this).attr("data-id"));custom_css=$("<div/>").text($(this).attr("data-css")).html();url=(b?"":"../")+"documents/centraladmin.php?process=slideshow&sid="+sid+"&css="+custom_css;$(this).attr("src",url)})}});